// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Pair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pair'](arg1, arg2, arg3, arg4);
}

export function RequestTransfer() {
  return window['go']['main']['App']['RequestTransfer']();
}

export function Select(arg1) {
  return window['go']['main']['App']['Select'](arg1);
}

export function Transfer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Transfer'](arg1, arg2, arg3, arg4, arg5);
}
