// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {crosschain} from '../models';

export function Connect():Promise<string>;

export function GetAddress(arg1:string):Promise<database.AccountChainInfo>;

export function Initialize(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Pair(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Transfer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<crosschain.TxHash>;
