// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAsset'](arg1, arg2, arg3);
}

export function AddLedger(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLedger'](arg1, arg2, arg3);
}

export function CalculateFee(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CalculateFee'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckCardConnection() {
  return window['go']['main']['App']['CheckCardConnection']();
}

export function CheckCardInitialized() {
  return window['go']['main']['App']['CheckCardInitialized']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function GetAddressAndAssets(arg1, arg2) {
  return window['go']['main']['App']['GetAddressAndAssets'](arg1, arg2);
}

export function GetAssetPrices(arg1, arg2) {
  return window['go']['main']['App']['GetAssetPrices'](arg1, arg2);
}

export function GetChainConfig(arg1) {
  return window['go']['main']['App']['GetChainConfig'](arg1);
}

export function GetChainConfigs() {
  return window['go']['main']['App']['GetChainConfigs']();
}

export function GetChains(arg1) {
  return window['go']['main']['App']['GetChains'](arg1);
}

export function GetNetwork() {
  return window['go']['main']['App']['GetNetwork']();
}

export function Initialize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Initialize'](arg1, arg2, arg3);
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function Pair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pair'](arg1, arg2, arg3, arg4);
}

export function SetNetwork(arg1) {
  return window['go']['main']['App']['SetNetwork'](arg1);
}

export function Transfer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Transfer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
